### ISSUE TITLE
Add travis telegram notifications

### ISSUE THREAD

**Issue by gz-c** [skycoin/cxo#146]
See https://github.com/skycoin/skycoin/pull/1259/files for how

**Comment by logrusorgru** [comment]
Thanks

**Comment by gz-c** [comment]
If you want them, instructions here https://github.com/kvld/travisci-telegram
They are announced in @skycoindevtravis on telegram

**Comment by logrusorgru** [comment]
So. I'm using

```yml
notifications:
  webhooks:
    urls:
      # Riot.im
      - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGtvc3R5YXJpbiUzQW1hdHJpeC5vcmcvJTIxRWNJT25NUXlUeUx3ZnRvVWxTJTNBbWF0cml4Lm9yZw"
      # Telegram Bot (https://github.com/kvld/travisci-telegram)
      - "https://fathomless-fjord-24024.herokuapp.com/notify"
    on_success: change  # always|never|change
    on_failure: always
    on_start: never
```
to get notifications on failure and on fix. I've added the bot to @skycoincxo and @skycoincxorus groups.
